# Generated by Django 3.2.5 on 2021-12-01 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 2, 1, 38, 23, 44587), editable=False),
        ),
    ]
