# Generated by Django 3.2.5 on 2021-11-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_notesm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotesM',
            new_name='Note',
        ),
    ]
