# Generated by Django 3.2.5 on 2021-11-23 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 19, 30, 41, 39005)),
        ),
    ]
